param1 = Intensity
param2 = Speed
param3 = Roundness
param4 = Declination
button1 = Stop all
button2 = Close
menu1 = File
menu2 = Edit
menu3 = Help
menu_item1 = Stop below
menu_item2 = Choose a file
menu_item3 = Suspend below
menu_item4 = Resume below
menu_item5 = Copy
menu_item6 = Paste
menu_item7 = Benchmark
menu_item8 = Usage
menu_item9 = About
message01 = Select range of wobble by mouse!
message02 = Frame Rate
default_speed = 15
default_image = 3386409319_7ca53351e8.jpg
maximum_image_size = 480
maximum_icon_size = 128
double_click_interval = 1000
frame_rate = 25
decrease = true
debug = false
icon_edit_copy = icon/editcopy_22x22.png
icon_edit_paste = icon/editpaste_22x22.png
icon_file_open = icon/fileopen_22x22.png
icon_stop = icon/player_stop_22x22.png
icon_pause = icon/player_pause_22x22.png
icon_restart = icon/quick_restart - copie_22x22.png
icon_about = icon/dialog-information_22x22.png
icon_usage = icon/help_22x22.png
about.title = About this?
about.html = html/about.html
help.title = Usage
help.html = html/help.html
application.name = Knocking Bird
application.version = ${project.version}
font.message = Serif
font.dialog = Serif
