param1 = Intensity
param2 = Speed
param3 = Roundness
param4 = Declination
button1 = Stop all
menu1 = File
menu2 = Edit
menu_item1 = Stop below
menu_item2 = Choose a file
menu_item3 = Suspend below
menu_item4 = Resume below
menu_item5 = Copy
menu_item6 = Paste
message01 = Select range of wobble by mouse!
default_image = 3386409319_7ca53351e8.jpg
maximum_image_size = 480
maximum_icon_size = 128
double_click_interval = 1000
frame_rate = 15