param1 = Intensity
param2 = Speed
param3 = Roundness
param4 = Declination
button1 = Stop all
menu_item1 = Stop below
menu_item2 = Choose a file
menu_item3 = Suspend below
menu_item4 = Resume below
message01 = Select range of wobble by mouse!