param1 = Intensity of wobble
param2 = Speed of wobble
param3 = Roundness of border
param4 = Declination of wobble
button1 = Stop all
menu_item1 = Stop wobble below
menu_item2 = Choose a file
message01 = Select range of wobble by mouse!